name: supply_integration
version: '1.0.0'
config-version: 2

profile: supply_integration

model-paths: ["models"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

seeds:
  supply_integration:
    pcm_templates:
      +column_types:
        template_name:     varchar
        template_category: varchar
        quantity_code:     varchar
        catalog_category:  varchar
    mko_product__hscode:
      +column_types:
        variant_id: varchar
        hs_code:    varchar
    xdc_production_days:
      +column_types:
        print_technique:      varchar
        print_color_quantity: integer
        area_min:             integer
        area_max:             integer
        quantity_min:         integer
        production_days:      integer

models:
  supply_integration:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
