supply_integration:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH', 'data/catalog_data_platform.duckdb') }}"
      extensions:
        - httpfs
      settings:
        s3_region: "{{ env_var('AWS_DEFAULT_REGION', 'eu-south-2') }}"
        s3_endpoint: "s3.eu-south-2.amazonaws.com"
        s3_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
